Extends the README.md with some more info
polderknowledge/parsy pull request #4
Opened 2017-01-13 10:54 UTC by jaapio

To create a better understanding for others what's going on I extended the
readme with some additional paragraphs.

2017-01-13 11:07 UTC, waltertamboer requested changes

2017-01-13 11:07 UTC, waltertamboer commented on README.md
> +This are some good reads that inspired us to start with this project:
`These` instead of `This`. Or `Here are some interesting resources`

2017-01-13 11:07 UTC, waltertamboer commented on README.md
> +We are sure that we are solving the same UX/UI problems every day. Sometimes the basic patterns and sometimes the
`Sometimes these problems relate to basic patterns and other times they are more complex`

2017-01-13 11:07 UTC, waltertamboer commented on README.md
> +everybody writing a pattern should be able to implement it. In many cases you will recognize patterns in a UI.
I would change this into `In many cases you will recognize patterns by spotting repetition in user interfaces.`

2017-01-13 11:07 UTC, waltertamboer commented on README.md
> +or it is just a lucky shot. Even if you are not sure if the problem you described is a pattern please submit your
`Even if you are not sure if the problem you described is a pattern` **comma** ` please submit your idea` *in order to help other people write even better proposals.*

2017-01-14 13:35 UTC, jaapio commented
Thanks @waltertamboer, I updated the file with your requested changes.

2017-01-15 21:59 UTC, waltertamboer approved these changes

2017-01-15 22:00 UTC, merged